import React from "react";
import MainHeaderNavRoot from "@/components/main/nav/MainHeaderNavRoot";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainPage: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <div className={"flex flex-col overflow-hidden w-full"}>
      <MainHeaderNavRoot />
      {children}
    </div>
  );
};

export default MainPage;
