import React from "react";
import type { Metadata } from "next";

import { MainHeaderNavRoot } from "@/features/main";
import { getServerSession } from "next-auth";
import { getNavBoardService } from "@/services/prisma-board-service";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainPage: React.FC<{
  children: React.ReactNode;
}> = async ({ children }) => {
  const session = await getServerSession();

  const boards = await getNavBoardService(session);

  return (
    <div className={"flex flex-col overflow-hidden w-screen h-screen"}>
      <MainHeaderNavRoot boards={boards} />
      {children}
    </div>
  );
};

export default MainPage;
