import MainSideNav from "@/components/nav/MainSideNav";
import "./globals.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import MainHeadNav from "@/components/nav/MainHeadNav";
import ReduxProvider from "@/utils/providers/redux-provider";
import MySessionProvider from "@/utils/providers/session-provider";
import { getServerSession } from "next-auth";
import prisma from "@/lib/prisma";
import { Board } from "prisma/prisma-client";
import MyQueryProvider from "@/utils/providers/react-query-provider";
import DeleteModal from "@/components/DeleteModal";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getBoards = async (email: string) => {
  try {
    const data = await prisma.board.findMany({
      where: {
        user: {
          email,
        },
      },
      select: {
        board_id: true,
        title: true,
      },
    });
    if (!data) {
      return [];
    }
    return data;
  } catch (error) {
    return [];
  }
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerSession();
  let data: Pick<Board, "board_id" | "title">[] = [];

  if (session && session?.user?.email) {
    data = await getBoards(session.user?.email);
  }
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-row w-screen h-screen overflow-hidden`}
      >
        <MyQueryProvider>
          <MySessionProvider session={session}>
            <ReduxProvider>
              <MainSideNav data={data} />
              <div
                className={`relative flex flex-col w-full h-full overflow-auto`}
              >
                <MainHeadNav data={data} />
                {children}
              </div>
              <div className={"absolute z-50 top-0 left-0 w-full h-full"}>
                <DeleteModal />
              </div>
            </ReduxProvider>
          </MySessionProvider>
        </MyQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
