import "./globals.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import MySessionProvider from "@/utils/providers/session-provider";
import { getServerSession } from "next-auth";
import MyQueryProvider from "@/utils/providers/react-query-provider";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden w-screen h-screen`}>
        <MyQueryProvider>
          <MySessionProvider session={session}>{children}</MySessionProvider>
        </MyQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
